export const profile = {
  name: "MUERHIIS",
  title: "视觉设计 / 后期制作",
  city: "杭州/上海",
  phone: "17826826676",
  email: "z126117909@163.com",
  wechat: "17826826676",
  availability: "尽快到岗",
  bio: [
    "浙江工商大学网络与新媒体专业（本科）27 届毕业生，GPA 4.17/5，专业排名 2/52。从传统拍摄剪辑，到后期制作（AE动效包装）/ AIGC ，持续用技术与审美把好故事做成好影像。",
    "B站深度使用用户，对游戏（二游PV、平面设计、二创MAD）、科技（相机、PC 等）感兴趣，ACG 爱好者。",
    "曾在遥望网络主导 AI 影视剧全流程制作，打造部门首部全站 Top 10 爆款：24 小时播放 800W+、累计 3600W+；也服务过 5 家头部金融客户，交付 10+ 条品牌视频。",
  ],
  education: {
    school: "浙江工商大学",
    college: "未来传播学院",
    major: "网络与新媒体 · 本科",
    period: "2023.09 — 2027.06",
    gpa: "4.17 / 5",
    rank: "2 / 52",
    role: "团支书",
    chips: ["CET-4/6 500+", "计算机二级", "普通话二甲"],
  },
};

export const internships = [
  {
    company: "遥望网络科技有限公司",
    role: "后期制作实习生",
    period: "2026.03 — 2026.06",
    metric: "24h 800W+ · 累计 3600W+ · 全站 Top 7",
    points: [
      "负责 AI 影视剧全流程制作，打造部门首部全站前十爆款：单平台 24 小时播放 800W+、累计 3600W+，另一平台全站第 7 名，实现部门 0→1 突破。",
      "AIGC 内容生产：剧本分镜头拆解、Prompt 标准化设计，人物 / 场景 / 道具核心资产批量生成与风格统一，独立完成素材生成与后期剪辑。",
      "深度参与公司 AI Agent 影视制作平台内测，从生产场景反馈关键 Bug 与应用痛点，多项优化建议被采纳。",
    ],
  },
  {
    company: "杭州卡朴文化传媒有限公司",
    role: "视频制作实习生",
    period: "2025.09 — 2025.12",
    metric: "5 家金融客户 · 10 余条成片",
    points: [
      "负责中意人寿、新华保险等金融甲方品牌活动与宣传视频的拍摄剪辑，完成从分镜沟通、现场拍摄到成片交付的全流程，累计服务 5 家头部客户。",
      "承接校内大型主题活动，针对大学生群体采用快节奏卡点剪辑、创意转场与热点 BGM 混剪，产出活动高光短视频。",
    ],
  },
  {
    company: "浙江广播电视集团",
    role: "编辑制作实习生",
    period: "2025.06 — 2025.08",
    metric: "多平台发布",
    points: [
      "参与国际事业部“文明探源·和合共生”俄罗斯青少年文化交流项目，使用索尼相机、稳定器负责视频拍摄，以剪映 / Pr / Ae 完成剪辑与后期合成，内容发布于“中国蓝国际”视频号等平台。",
    ],
  },
];

export const experiences = [
  {
    title: "贵州茅台 TVC",
    tag: "AI 生成 + Ae 后期",
    desc: "使用 Lovart 平台调用 Nano banana 等模型生成 AI 图片，Seedance 2.0 生成视频，Ae 将 AI 视频资源与实拍素材后期合成。",
    tools: ["Lovart", "Nano banana", "Seedance 2.0", "After Effects"],
  },
  {
    title: "胤秋 · Ae 商用模板",
    tag: "Ae 合成 / 3D",
    desc: "商用传统文化向运营短视频 Ae 模板：VideoCopilot Element 建模渲染羊皮卷轴并制作 3D 动画，分形杂色模拟水墨晕染效果。",
    tools: ["After Effects", "Element 3D", "分形杂色"],
  },
  {
    title: "00 后传统村落合伙人",
    tag: "社会实践负责人",
    desc: "与浙江日报潮新闻合作组织 6 场直播，全流程负责 2 条采访视频的拍摄与剪辑；获人民日报、北京青年报、央视频等报道，全网浏览量超 1700W。",
    tools: ["直播", "采访纪录片", "Premiere"],
  },
];

// ---------- 精选项目（对应简历的几件作品） ----------
export const works = [
  {
    id: "zhongmodi-ae",
    index: "01",
    title: "终末地 · 游戏二创",
    subtitle: "AE 动效 · 游戏同人短片",
    category: "AE",
    role: "剪辑 / 合成",
    duration: "00:14",
    metrics: ["片长 00:14", "AE 合成", "游戏同人"],
    desc: "使用 After Effects 完成动效设计与后期合成，围绕《终末地》世界观创作的游戏同人短片，节奏卡点与视觉冲击并重。",
    tags: ["After Effects", "游戏二创", "动效"],
    image: "/works/posters/ae-zhongmodi.webp",
    video: "/works/videos/ae-zhongmodi.mp4",
    ratio: { w: 16, h: 9 },
    featured: true,
  },
  {
    id: "design-qianmo",
    index: "02",
    title: "缄默德克萨斯 · 视觉设计",
    subtitle: "PS 平面设计 · 角色视觉",
    category: "平面设计",
    role: "Photoshop / 平面",
    metrics: ["角色视觉", "PS 排版", "仿制练习"],
    desc: "以《明日方舟》干员缄默德克萨斯为主题的角色视觉设计，通过 Photoshop 完成人物合成、排版与整体风格化处理。",
    tags: ["Photoshop", "平面设计", "明日方舟"],
    image: "/works/images/design-qianmo.webp",
    ratio: { w: 2410, h: 1320 },
  },
  {
    id: "ae-yinqiu",
    index: "03",
    title: "胤秋 · 诗词视频 AE 模板",
    subtitle: "商用模板 · 传统文化向",
    category: "AE",
    role: "合成 / 3D",
    duration: "00:11",
    metrics: ["片长 00:11", "商用上架", "3D 卷轴"],
    desc: "对应简历中的胤秋商用模板项目：VideoCopilot Element 建模渲染羊皮卷轴 3D 动画，分形杂色模拟水墨晕染效果。",
    tags: ["After Effects", "Element 3D", "水墨"],
    image: "/works/posters/ae-yinqiu.webp",
    video: "/works/videos/ae-yinqiu.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "clip-zglgj-1",
    index: "04",
    title: "中国蓝国际 · 文化交流短片 01",
    subtitle: "浙江广电实习 · 拍摄与剪辑",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑 / 合成",
    duration: "00:42",
    metrics: ["片长 00:42", "浙江广电", "多平台发布"],
    desc: "对应简历中的浙江广电实习：参与“文明探源·和合共生”文化交流项目，负责视频拍摄与后期剪辑合成。",
    tags: ["拍摄", "Premiere", "After Effects"],
    image: "/works/posters/clip-zglgj-1.webp",
    video: "/works/videos/clip-zglgj-1.mp4",
    ratio: { w: 9, h: 16 },
  },
  {
    id: "clip-hengshanwu",
    index: "05",
    title: "湖州安吉横山坞宣传片",
    subtitle: "宣传片 00后传统村落合伙人社会实践",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑",
    duration: "03:57",
    metrics: ["片长 03:57", "宣传片", "1700W+ 全网浏览"],
    desc: "湖州安吉横山坞宣传片，负责从拍摄到成片的全流程制作。",
    tags: ["拍摄", "Premiere", "宣传片"],
    image: "/works/posters/clip-hengshanwu.webp",
    video: "/works/videos/clip-hengshanwu.mp4",
    ratio: { w: 16, h: 9 },
  },
];

// ---------- 全部作品（17 件，按用户指定顺序 + 分类） ----------
export const allWorks = [
  {
    id: "zhongmodi-ae",
    index: "01",
    title: "终末地 · 游戏二创",
    subtitle: "AE 动效 · 游戏同人短片",
    category: "AE",
    role: "剪辑 / 合成",
    duration: "00:14",
    desc: "使用 After Effects 完成动效设计与后期合成，围绕《终末地》世界观创作的游戏同人短片。",
    tags: ["After Effects", "游戏二创", "动效"],
    image: "/works/posters/ae-zhongmodi.webp",
    video: "/works/videos/ae-zhongmodi.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "design-qianmo",
    index: "02",
    title: "缄默德克萨斯 · 角色平面设计",
    subtitle: "PS 平面设计 · 角色视觉",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "以《明日方舟》干员缄默德克萨斯为主题的角色视觉设计，完成人物合成、排版与整体风格化处理。",
    tags: ["Photoshop", "平面设计", "明日方舟"],
    image: "/works/images/design-qianmo.webp",
    ratio: { w: 2410, h: 1320 },
  },
  {
    id: "design-shuangkanban",
    index: "03",
    title: "游戏看板娘 · 角色平面设计",
    subtitle: "PS 平面设计 · 看板娘主题",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "以看板娘为主题的平面设计仿制作品，通过 PS 完成人物处理、版式与氛围塑造。",
    tags: ["Photoshop", "平面设计", "仿制练习"],
    image: "/works/images/design-shuangkanban.webp",
    ratio: { w: 1920, h: 1440 },
  },
  {
    id: "design-amiya",
    index: "04",
    title: "医疗阿米娅 · 角色平面设计",
    subtitle: "PS 平面设计 · 角色视觉",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "以《明日方舟》医疗阿米娅为主题的角色视觉设计，注重人物质感与信息层级的平衡。",
    tags: ["Photoshop", "平面设计", "明日方舟"],
    image: "/works/images/design-amiya.webp",
    ratio: { w: 1920, h: 1440 },
  },
  {
    id: "design-yanying",
    index: "05",
    title: "焰影苇草 · 夏卉 · 角色平面设计",
    subtitle: "PS 平面设计 · 皮肤主题",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "以《明日方舟》焰影苇草「夏卉」皮肤为主题的角色视觉设计，完成画面合成与风格化处理。",
    tags: ["Photoshop", "平面设计", "明日方舟"],
    image: "/works/images/design-yanying.webp",
    ratio: { w: 2560, h: 1440 },
  },
  {
    id: "ae-dongman-pv",
    index: "06",
    title: "动漫 PV 练习",
    subtitle: "AE 动画 · 卡点节奏",
    category: "AE",
    role: "动画 / 剪辑",
    duration: "03:25",
    desc: "AE 动画节奏练习：镜头转场、音乐卡点与动效包装的 PV 风格短片。",
    tags: ["After Effects", "动画", "卡点剪辑"],
    image: "/works/posters/ae-dongman-pv.webp",
    video: "/works/videos/ae-dongman-pv.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "ae-yinqiu",
    index: "07",
    title: "胤秋 · 诗词视频 AE 模板",
    subtitle: "商用模板 · 传统文化向",
    category: "AE",
    role: "合成 / 3D",
    duration: "00:11",
    desc: "对应简历中的胤秋商用模板项目：3D 羊皮卷轴动画 + 分形杂色水墨晕染。",
    tags: ["After Effects", "Element 3D", "水墨"],
    image: "/works/posters/ae-yinqiu.webp",
    video: "/works/videos/ae-yinqiu.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "ae-xuerong",
    index: "08",
    title: "微电影《雪融之时》宣传片",
    subtitle: "AE 包装 · 宣传片",
    category: "AE",
    role: "剪辑 / 包装",
    duration: "00:30",
    desc: "微电影《雪融之时》宣传片，负责动效包装与后期剪辑。",
    tags: ["After Effects", "宣传片", "包装"],
    image: "/works/posters/ae-xuerong.webp",
    video: "/works/videos/ae-xuerong.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "ae-c5-dianjing",
    index: "09",
    title: "C5 大神电竞 · 高校赛宣传片",
    subtitle: "AE 动效 · 赛事宣传",
    category: "AE",
    role: "剪辑 / 动效",
    duration: "00:34",
    desc: "C5 大神电竞杭州高校赛宣传片，负责动效设计与成片剪辑。",
    tags: ["After Effects", "电竞", "宣传片"],
    image: "/works/posters/ae-c5-dianjing.webp",
    video: "/works/videos/ae-c5-dianjing.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "design-zhongmodi-1",
    index: "10",
    title: "终末地 · 角色二创（诀）01",
    subtitle: "平面设计 · 角色海报",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "《终末地》角色「诀」的二创视觉海报，围绕角色气质完成构图与氛围设计。",
    tags: ["Photoshop", "平面设计", "终末地"],
    image: "/works/images/design-zhongmodi-1.webp",
    ratio: { w: 1920, h: 1080 },
  },
  {
    id: "design-zhongmodi-2",
    index: "11",
    title: "终末地 · 角色二创（诀）02",
    subtitle: "平面设计 · 角色海报",
    category: "平面设计",
    role: "Photoshop / 平面",
    desc: "《终末地》角色「诀」的二创视觉海报第二版，强化视觉张力与细节层次。",
    tags: ["Photoshop", "平面设计", "终末地"],
    image: "/works/images/design-zhongmodi-2.webp",
    ratio: { w: 1920, h: 1080 },
  },
  {
    id: "clip-zglgj-1",
    index: "12",
    title: "中国蓝国际 · 文化交流短片 01",
    subtitle: "浙江广电实习 · 拍摄与剪辑",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑 / 合成",
    duration: "00:42",
    desc: "对应简历中的浙江广电实习：文化交流项目成片，负责视频拍摄与后期剪辑合成。",
    tags: ["拍摄", "Premiere", "After Effects"],
    image: "/works/posters/clip-zglgj-1.webp",
    video: "/works/videos/clip-zglgj-1.mp4",
    ratio: { w: 9, h: 16 },
  },
  {
    id: "clip-zglgj-2",
    index: "13",
    title: "中国蓝国际 · 文化交流短片 02",
    subtitle: "浙江广电实习 · 拍摄与剪辑",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑 / 合成",
    duration: "01:35",
    desc: "对应简历中的浙江广电实习：文化交流项目成片，负责视频拍摄与后期剪辑合成。",
    tags: ["拍摄", "Premiere", "After Effects"],
    image: "/works/posters/clip-zglgj-2.webp",
    video: "/works/videos/clip-zglgj-2.mp4",
    ratio: { w: 9, h: 16 },
  },
  {
    id: "clip-zglgj-3",
    index: "14",
    title: "中国蓝国际 · 文化交流短片 03",
    subtitle: "浙江广电实习 · 拍摄与剪辑",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑 / 合成",
    duration: "00:41",
    desc: "对应简历中的浙江广电实习：文化交流项目成片，负责视频拍摄与后期剪辑合成。",
    tags: ["拍摄", "Premiere", "After Effects"],
    image: "/works/posters/clip-zglgj-3.webp",
    video: "/works/videos/clip-zglgj-3.mp4",
    ratio: { w: 9, h: 16 },
  },
  {
    id: "clip-hengshanwu",
    index: "15",
    title: "湖州安吉横山坞宣传片",
    subtitle: "宣传片 00后传统村落合伙人社会实践",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑",
    duration: "03:57",
    desc: "湖州安吉横山坞宣传片，负责从拍摄到成片的全流程制作。",
    tags: ["拍摄", "Premiere", "宣传片"],
    image: "/works/posters/clip-hengshanwu.webp",
    video: "/works/videos/clip-hengshanwu.mp4",
    ratio: { w: 16, h: 9 },
  },
  {
    id: "clip-baziqiao",
    index: "16",
    title: "绍兴八字桥人物采访",
    subtitle: "采访 00后传统村落合伙人社会实践",
    category: "拍摄与剪辑",
    role: "拍摄 / 剪辑",
    duration: "04:14",
    desc: "绍兴八字桥人物采访，负责采访拍摄与成片剪辑。",
    tags: ["拍摄", "Premiere", "采访"],
    image: "/works/posters/clip-baziqiao.webp",
    video: "/works/videos/clip-baziqiao.mp4",
    ratio: { w: 16, h: 9 },
  },
];

export const workCategories = [
  {
    id: "main",
    label: "主要作品",
    ids: ["zhongmodi-ae", "design-qianmo", "design-shuangkanban"],
  },
  {
    id: "graphic",
    label: "平面设计作品",
    ids: [
      "design-amiya",
      "design-yanying",
      "design-zhongmodi-1",
      "design-zhongmodi-2",
    ],
  },
  {
    id: "ae",
    label: "AE 作品",
    ids: ["ae-dongman-pv", "ae-yinqiu", "ae-xuerong", "ae-c5-dianjing"],
  },
  {
    id: "film",
    label: "拍摄与剪辑作品",
    ids: [
      "clip-zglgj-1",
      "clip-zglgj-2",
      "clip-zglgj-3",
      "clip-hengshanwu",
      "clip-baziqiao",
    ],
  },
];

export const strengths = [
  {
    index: "01",
    title: "动效与后期合成",
    desc: "AE 关键帧速度曲线、蒙版遮罩、Trapcode / E3D 粒子，Blender 材质与几何节点，PS / Pr 平面与剪辑。",
    tools: ["After Effects", "Premiere", "Blender", "Photoshop"],
    icon: "layers",
    size: "lg",
  },
  {
    index: "02",
    title: "爆款内容思维",
    desc: "以数据与叙事节奏驱动创作，24 小时 800W+、累计 3600W+ 播放验证。",
    tools: ["数据复盘", "热点洞察"],
    icon: "chart",
  },
  {
    index: "03",
    title: "产品协作与测试",
    desc: "深度参与 AI Agent 影视制作平台内测，全链路测试并反馈关键 Bug 与痛点，优化建议被采纳、提升平台易用性。",
    tools: ["全链路测试", "需求反馈"],
    icon: "users",
  },
  {
    index: "04",
    title: "视觉与叙事审美",
    desc: "从分镜到成片的整体视觉把控，全国大学生新媒体创意大赛、大广赛等多次获奖，多奖项与奖学金背书。",
    tools: ["分镜设计", "色彩 / 节奏"],
    icon: "eye",
  },
  {
    index: "05",
    title: "AIGC 影视全流程",
    desc: "分镜拆解 → Prompt 标准化 → 人物 / 场景 / 道具批量生成 → 剪辑成片，风格统一、节奏可控，并具备产品级协作能力。",
    tools: ["Seedance", "Nano banana", "Lovart", "Gemini"],
    icon: "spark",
  },
];

export const awards = [
  "大广赛 · 校赛一等奖 / 省赛优秀奖 / 入围国赛",
  "全国大学生新媒体创意大赛 · 省级三等奖 / 入围国赛",
  "浙江省政府奖学金",
  "校三好学生 · 优秀学生干部 · 综合奖学金一等奖",
];

export const stats = [
  { value: "3600W+", label: "单条视频累计播放量" },
  { value: "多段", label: "一线公司实习" },
  { value: "10+", label: "品牌视频交付" },
];
